settings:
  nacos:
    host: 192.168.1.15
    port: 8848
    namespace: dev
    group: dev
    dataid: sms-gateway
  logger:
    # 日志存放路径
    path: temp/logs
    # 日志输出，file：文件，default：命令行，其他：命令行
    stdout: '' #控制台日志，启用后，不输出到文件
    # 日志等级, trace, debug, info, warn, error, fatal
    level: trace
    # 数据库日志开关
    enableddb: true